API_BASE = "https://bfo-backend.onrender.com"

TRANSLATIONS = {
    "en": {
        "app_title": "Jan Seva Portal",
        
        "app_subtitle": "AI-Powered Citizen Grievance System",
        "select_language": "Select Your Language",
        "continue": "Continue",
        "login": "Login",
        "signup": "Sign Up",
        "logout": "Logout",
        "phone": "Phone Number",
        "name": "Full Name",
        "address": "Address",
        "email": "Email",
        "password": "Password",
        "send_otp": "Send OTP",
        "verify_otp": "Verify OTP",
        "otp": "Enter OTP",
        "dept_code": "Department Code",
        "file_complaint": "File Complaint",
        "track_complaint": "Track Complaint",
        "govt_schemes": "Govt Schemes",
        "ai_assistant": "AI Assistant",
        "dashboard": "Dashboard",
        "hello": "Hello",
        "category": "Category",
        "description": "Describe your issue",
        "location": "Location",
        "submit": "Submit Complaint",
        "status_pending": "Pending",
        "status_inprogress": "In Progress",
        "status_resolved": "Resolved",
        "priority_high": "High",
        "priority_medium": "Medium",
        "priority_low": "Low",
        "total": "Total",
        "pending": "Pending",
        "in_progress": "In Progress",
        "resolved": "Resolved",
        "notifications": "Notifications",
        "chat_placeholder": "Ask me anything...",
        "send": "Send",
        "voice_input": "Voice Input",
        "read_aloud": "Read Aloud",
        "back": "Back",
        "user_login": "Citizen Login",
        "official_login": "Official Login",
        "admin_login": "Admin Login",
        "register": "Register",
        "greeting_morning": "Good Morning",
        "greeting_afternoon": "Good Afternoon",
        "greeting_evening": "Good Evening",
        "complaint_filed": "Complaint filed successfully!",
        "your_complaints": "Your Complaints",
        "no_complaints": "No complaints filed yet.",
        "feedback_q": "Was your complaint resolved?",
        "yes_resolved": "👍 Resolved",
        "not_resolved": "❌ Not Resolved",
        "timeline": "Timeline",
        "dept_code_hint": "Get code from your department admin",
        "schemes": "Government Schemes",
        "scheme_detail": "Scheme Details",
        "approve": "Approve",
        "pending_approvals": "Pending Approvals",
        "create_dept": "Create Department",
        "all_complaints": "All Complaints",
        "voice_listening": "🎤 Listening... Speak now",
        "voice_done": "✅ Voice captured",
        "get_location": "📍 Get My Location",
        "location_fetching": "Fetching location...",
        "dark_mode": "🌙 Dark Mode",
        "light_mode": "☀️ Light Mode",
        # Admin & Official additional keys
        "overview": "Overview",
        "departments": "Departments",
        "officials": "Officials",
        "leaderboard": "Leaderboard",
        "predictive_ai": "Predictive AI",
        "sla_tracking": "SLA Tracking",
        "heatmap": "Heatmap",
        "quick_actions": "Quick Actions",
        "your_performance": "Your Performance",
        "total_complaints": "Total Complaints",
        "active": "Active",
        "pending_approval": "Pending Approval",
        "approved_officials": "Approved Officials",
        "resolution_rate": "Resolution Rate",
        "avg_rating": "Average Rating",
        "success_rate": "Success Rate",
        "assigned": "Assigned",
        "filter": "Filter",
        "search": "Search",
        "status": "Status",
        "priority": "Priority",
        "all": "All",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "refresh": "Refresh",
        "export_csv": "Export CSV",
        "how_it_works": "How It Works",
        "key_features": "Key Features",
        "need_help": "Need Help?",
        "contact_support": "Contact Support",
        "file_your_first_complaint": "File Your First Complaint",
        "pro_tip": "Pro Tip",
        "view_all": "View All",
        "rate_service": "Rate the Service",
        "confirm_resolution": "Confirm Resolution",
        "satisfied": "Satisfied",
        "not_satisfied": "Not Satisfied",
        "submit_rating": "Submit Rating",
        "optional": "optional",
        "complaint_resolved": "Complaint Resolved",
        "please_confirm": "Please Confirm",
        "respond_by": "Respond by",
        "auto_closes": "auto-closes",
        "overdue": "OVERDUE",
        "expected_by": "Expected by",
        "no_data": "No data available",
        "loading": "Loading...",
        "error": "Error",
    },
    "hi": {
        "app_title": "जन सेवा पोर्टल",
        "app_subtitle": "AI-संचालित नागरिक शिकायत प्रणाली",
        "complaints": "शिकायतें",
        "all_complaints": "सभी शिकायतें",
        "select_language": "अपनी भाषा चुनें",
        "continue": "आगे बढ़ें",
        "login": "लॉगिन",
        "signup": "साइन अप",
        "logout": "लॉगआउट",
        "phone": "फ़ोन नंबर",
        "name": "पूरा नाम",
        "address": "पता",
        "email": "ईमेल",
        "password": "पासवर्ड",
        "send_otp": "OTP भेजें",
        "verify_otp": "OTP सत्यापित करें",
        "otp": "OTP डालें",
        "dept_code": "विभाग कोड",
        "file_complaint": "शिकायत दर्ज करें",
        "track_complaint": "शिकायत ट्रैक करें",
        "govt_schemes": "सरकारी योजनाएं",
        "ai_assistant": "AI सहायक",
        "dashboard": "डैशबोर्ड",
        "hello": "नमस्ते",
        "category": "श्रेणी",
        "description": "अपनी समस्या बताएं",
        "location": "स्थान",
        "submit": "शिकायत जमा करें",
        "status_pending": "लंबित",
        "status_inprogress": "प्रगति में",
        "status_resolved": "हल हो गई",
        "priority_high": "उच्च",
        "priority_medium": "मध्यम",
        "priority_low": "निम्न",
        "total": "कुल",
        "pending": "लंबित",
        "in_progress": "प्रगति में",
        "resolved": "हल हो गई",
        "notifications": "सूचनाएं",
        "chat_placeholder": "कुछ भी पूछें...",
        "send": "भेजें",
        "voice_input": "आवाज़ इनपुट",
        "read_aloud": "ज़ोर से पढ़ें",
        "back": "वापस",
        "user_login": "नागरिक लॉगिन",
        "official_login": "अधिकारी लॉगिन",
        "admin_login": "एडमिन लॉगिन",
        "register": "पंजीकरण",
        "greeting_morning": "सुप्रभात",
        "greeting_afternoon": "नमस्कार",
        "greeting_evening": "शुभ संध्या",
        "complaint_filed": "शिकायत सफलतापूर्वक दर्ज हो गई!",
        "your_complaints": "आपकी शिकायतें",
        "no_complaints": "अभी तक कोई शिकायत नहीं।",
        "feedback_q": "क्या आपकी शिकायत हल हो गई?",
        "yes_resolved": "👍 हल हो गई",
        "not_resolved": "❌ हल नहीं हुई",
        "timeline": "टाइमलाइन",
        "dept_code_hint": "विभाग एडमिन से कोड प्राप्त करें",
        "schemes": "सरकारी योजनाएं",
        "scheme_detail": "योजना विवरण",
        "approve": "स्वीकृत करें",
        "pending_approvals": "अनुमोदन बाकी",
        "create_dept": "विभाग बनाएं",
        "all_complaints": "सभी शिकायतें",
        "voice_listening": "🎤 सुन रहे हैं... बोलें",
        "voice_done": "✅ आवाज़ दर्ज",
        "get_location": "📍 मेरा स्थान पाएं",
        "location_fetching": "स्थान ढूंढ रहे हैं...",
        "dark_mode": "🌙 डार्क मोड",
        "light_mode": "☀️ लाइट मोड",
        # Admin & Official translations
        "overview": "अवलोकन",
        "departments": "विभाग",
        "officials": "अधिकारी",
        "leaderboard": "लीडरबोर्ड",
        "predictive_ai": "पूर्वानुमान AI",
        "sla_tracking": "SLA ट्रैकिंग",
        "heatmap": "हीटमैप",
        "quick_actions": "त्वरित कार्रवाई",
        "your_performance": "आपका प्रदर्शन",
        "total_complaints": "कुल शिकायतें",
        "active": "सक्रिय",
        "pending_approval": "अनुमोदन लंबित",
        "approved_officials": "स्वीकृत अधिकारी",
        "resolution_rate": "समाधान दर",
        "avg_rating": "औसत रेटिंग",
        "success_rate": "सफलता दर",
        "assigned": "असाइन किए गए",
        "filter": "फ़िल्टर",
        "search": "खोजें",
        "status": "स्थिति",
        "priority": "प्राथमिकता",
        "all": "सभी",
        "high": "उच्च",
        "medium": "मध्यम",
        "low": "निम्न",
        "refresh": "ताज़ा करें",
        "export_csv": "CSV निर्यात करें",
        "how_it_works": "यह कैसे काम करता है",
        "key_features": "मुख्य विशेषताएं",
        "need_help": "मदद चाहिए?",
        "contact_support": "सहायता से संपर्क करें",
        "file_your_first_complaint": "अपनी पहली शिकायत दर्ज करें",
        "pro_tip": "टिप",
        "view_all": "सभी देखें",
        "rate_service": "सेवा को रेट करें",
        "confirm_resolution": "समाधान की पुष्टि करें",
        "satisfied": "संतुष्ट",
        "not_satisfied": "असंतुष्ट",
        "submit_rating": "रेटिंग जमा करें",
        "optional": "वैकल्पिक",
        "complaint_resolved": "शिकायत हल हो गई",
        "please_confirm": "कृपया पुष्टि करें",
        "respond_by": "उत्तर दें",
        "auto_closes": "अपने आप बंद हो जाएगा",
        "overdue": "समय सीमा समाप्त",
        "expected_by": "अपेक्षित तिथि",
        "no_data": "कोई डेटा उपलब्ध नहीं",
        "loading": "लोड हो रहा है...",
        "error": "त्रुटि",
    }
}

# Chatbot responses – keep as you have (already bilingual)


CHATBOT_RESPONSES = {
    "en": {
        "greet": ["Hello! I'm your AI assistant. How can I help you today? 😊", "Hi there! I'm here to help with your grievances and government schemes."],
        "complaint": "To file a complaint, click on 'File Complaint' from your dashboard. You can describe your issue in text or use voice input.",
        "track": "To track your complaint, go to 'Track Complaint' and enter your complaint ID (e.g., GR12345678).",
        "scheme": "I can help you learn about government schemes. Go to 'Govt Schemes' section to see all available schemes.",
        "water": "Water-related complaints are handled by the Water Supply Department. File your complaint and it will be auto-routed.",
        "electricity": "Electricity complaints go to the Electricity Department. File your complaint for quick resolution.",
        "road": "Road and pothole complaints are handled by the Public Works Department.",
        "default": "I'm here to help! You can ask me about filing complaints, tracking status, or government schemes. 🙏"
    },
    "hi": {
        "greet": ["नमस्ते! मैं आपका AI सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं? 😊", "नमस्ते! मैं आपकी शिकायतों और सरकारी योजनाओं में मदद के लिए यहां हूं।"],
        "complaint": "शिकायत दर्ज करने के लिए, अपने डैशबोर्ड से 'शिकायत दर्ज करें' पर क्लिक करें। आप टेक्स्ट या आवाज़ से समस्या बता सकते हैं।",
        "track": "शिकायत ट्रैक करने के लिए, 'शिकायत ट्रैक करें' पर जाएं और अपना शिकायत ID डालें।",
        "scheme": "मैं सरकारी योजनाओं के बारे में जानकारी दे सकता हूं। 'सरकारी योजनाएं' अनुभाग में जाएं।",
        "water": "पानी से संबंधित शिकायतें जल आपूर्ति विभाग को भेजी जाती हैं।",
        "electricity": "बिजली की शिकायतें विद्युत विभाग को जाती हैं।",
        "road": "सड़क और गड्ढों की शिकायतें लोक निर्माण विभाग को जाती हैं।",
        "default": "मैं यहां मदद के लिए हूं! शिकायत दर्ज करने, ट्रैक करने, या सरकारी योजनाओं के बारे में पूछ सकते हैं। 🙏"
    }
}
