services:
  # Backend API
  - type: web
    name: bfo-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bfo-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"

  # Frontend Streamlit
  - type: web
    name: bfo-frontendss
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: bfo-db
    databaseName: janseva
    user: janseva_user
    plan: free